### Base URL
@baseUrl = http://localhost:5169/api/users

### Criar novo usuário (público - sem autenticação)
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "João da Silva",
  "email": "joao@email.com",
  "password": "123456"
}

### Listar todos os usuários (requer token JWT)
GET {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqb2FvQGVtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiVXNlcklkIjoiMyIsImV4cCI6MTc0NzAyMzk4MSwiaXNzIjoiQVBJX1NUUkVBTUVSIiwiYXVkIjoiQVBJX1NUUkVBTUVSX1VzZXJzIn0.YgBToZfhYFmf0UIFqI9Ms0KnQl4PWI0213BCWjAAGUQ
 

### Obter um usuário específico (ID = 1)
GET {{baseUrl}}/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqb2FvQGVtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiVXNlcklkIjoiMyIsImV4cCI6MTc0NzAyMzk4MSwiaXNzIjoiQVBJX1NUUkVBTUVSIiwiYXVkIjoiQVBJX1NUUkVBTUVSX1VzZXJzIn0.YgBToZfhYFmf0UIFqI9Ms0KnQl4PWI0213BCWjAAGUQ


### Atualizar usuário (ID = 1)
PUT {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqb2FvQGVtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiVXNlcklkIjoiMyIsImV4cCI6MTc0NzAyMzk4MSwiaXNzIjoiQVBJX1NUUkVBTUVSIiwiYXVkIjoiQVBJX1NUUkVBTUVSX1VzZXJzIn0.YgBToZfhYFmf0UIFqI9Ms0KnQl4PWI0213BCWjAAGUQ

{
  "name": "João Atualizado",
  "email": "joao_novo@email.com",
  "password": "novaSenha123"
}

### Deletar usuário (ID = 1)
DELETE {{baseUrl}}/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqb2FvQGVtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiVXNlcklkIjoiMyIsImV4cCI6MTc0NzAyMzk4MSwiaXNzIjoiQVBJX1NUUkVBTUVSIiwiYXVkIjoiQVBJX1NUUkVBTUVSX1VzZXJzIn0.YgBToZfhYFmf0UIFqI9Ms0KnQl4PWI0213BCWjAAGUQ

